articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_edit'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('new/', views.ArticleCreateView.as_view(), name='article_new'),
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pages.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

articles/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:article_detail', args=[str(self.id)])


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('articles:article_list')

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(default=0)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy

from . import models


class ArticleListView(LoginRequiredMixin, ListView):
    model = models.Article
    template_name = 'articles/article_list.html'
    login_url = 'login'


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = models.Article
    template_name = 'articles/article_detail.html'
    login_url = 'login'


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Article
    fields = ['title', 'body', ]
    template_name = 'articles/article_edit.html'
    login_url = 'login'


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy('articles:article_list')
    login_url = 'login'


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = models.Article
    template_name = 'articles/article_new.html'
    fields = ['title', 'body', ]
    login_url = 'login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'home.html'

users/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

articles/templates/articles/article_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Delete</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ article.title }}"?</p>
        <button class="btn btn-danger ml-2" type="submit">Confirm</button>
    </form>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="article-entry">
        <h2>{{ object.title }}</h2>
        <p>by {{ object.author }} | {{ object.body }}</p>
        <p>{{ object.body }}</p>
    </div>
    <p>
        Back to <a href="{% url 'articles:article_edit' article.pk %}">Edit</a> |
    <a href="{% url 'articles:article_delete' article.pk %}">Delete</a>
    </p>
    <p>Back to <a href="{% url 'articles:article_list' %}">All Articles</a>.</p>
{% endblock content %}

articles/templates/articles/article_edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Edit</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-info ml-2" type="submit">Update</button>
    </form>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% block title %}Articles{% endblock %}

{% block content %}
    {% for article in object_list %}
    <div class="card">
        <div class="card-header">
            <span class="font-weight-bold"><a href="{% url 'articles:article_detail' article.pk %}">{{ article.title }}</a></span> &middot;
            <span class="text-muted">by {{ article.author }} | {{ article.date }}</span>
        </div>
        <div class="card-body">
            {{ article.body }}
            <a href="{% url 'articles:article_edit' article.pk %}">Edit</a> |
            <a href="{% url 'articles:article_delete' article.pk %}">Delete</a>
        </div>
    <div class="card-footer">
        <p>Комментарии: </p>
        {% for comment in article.comments.all %}
            <p>
                <span class="font-weight-bolt">{{ comment.author }} &middot;</span>
                {{ comment }}
            </p>
            {% endfor %}
    </div>
    </div>
    <br>
    {% endfor %}
{% endblock content %}

articles/templates/articles/article_new.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <h1>New article</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
    </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{% block title %}Newspaper App{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'pages:home' %}">My Newspaper</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="{% url 'articles:article_new' %}">+ New Article</a>
                  <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                Log Out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
            Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
            Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Newspaper App</h1>
        <p class="lead">A Newspaper website built with Django.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'articles:article_list' %}" role="button">
                View All Articles
            </a>
            {% if user.is_authenticated %}
        <a class="btn btn-primary btn-lg" href="{% url 'articles:article_new' %}" role="button">
                + New Article
        </a>
    {% endif %}
        </p>
    </div>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
    <button class="btn btn-success" type="submit">Sign Up</button>
    </form>
{% endblock content %}